### ISSUE TITLE
⚠️ Change default branch to "main"

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#47]
Instructions here https://www.kubernetes.dev/resources/rename/

## Anytime

- [x] If a presubmit or postsubmit prowjob triggers on the master branch (branches field of the prowjob), add the main branch to the list (see kubernetes/test-infra#20665 for an example).
- [x] If the milestone_applier prow config references the master branch, add the main branch to the config (see kubernetes/test-infra#20675 for an example).
- [x] If the branch_protection prow config references the master branch, add the main branch to the config.

## Just before rename 

- [x] periodic prowjobs, or any prowjob that mentions the master
- [x] If a prowjob mentions master in its name, rename the job to not include the branch name
- [x] If a prowjob calls scripts or code in your repo that explicitly reference master

## Finalizing

- [x] Set remote `head` to track main
- [x] Rename the default branch from master to main 
- [x] #66 fix apidiff branch name
## Post-rename

- [x] If a prowjob still references the master branch in the branches field, remove the master branch
  - [x] https://github.com/kubernetes/test-infra/pull/22309 
- [x] ~If the milestone_applier prow config references the master branch, remove it from the config.~
- [x] Send out comms

/kind cleanup
/wg naming

**Comment by spiffxp** [comment]
So I see you checked a bunch of boxes but what exactly did you do? Do you have links to PRs or descriptions of why you're good to go?

**Comment by christopherhein** [comment]
Yea, we don't actually have a lot of work cause of this being a relatively new repo, we only had one Prow job which was added recently with this issue in mind, note our only Prow presubmit jobs - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-nested/cluster-api-provider-nested-presubmits.yaml#L10 and in those the scripts that are called act solely on the branch that was pulled. Both `branch_protection` and `milestone_applier` haven't been configured yet.

Additionally, We discussed this on today's CAPN Office hours as well - https://www.youtube.com/watch?v=-bbUzYKHFls&t=5s to pre-emptively get folks ready for when the change goes into effect.

**Comment by spiffxp** [comment]
You'll want to take care of https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/fefd2138922b0d24a7ebe8c569cef0bc2f42e242/Makefile#L147

But +1 as a github admin to go ahead

**Comment by christopherhein** [comment]
Good catch, thank you, I'll get that fixed up.

**Comment by christopherhein** [comment]
Branch has been changed in the Githuh UI and not is tracking the `main` branch. https://github.com/kubernetes-sigs/cluster-api-provider-nested/tree/main

**Comment by christopherhein** [comment]
/close
Thanks folks for all your help on this! 🎉  
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/Woe731ONmBc
